# port
server:
  port: 8080


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zhuyz.admin_user.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/admin_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
